export * from './home.page';
export * from './not-found.page';
export * from './login.page';
export * from './register.page';
export * from './verification.page';
export * from './restaurant-details.page';
export * from './my-profile.page';
export * from './edit-profile.page';
export * from './category.page';
